name: CD

on:
  push:
    branches:
      - master
      - sequoia-tahoe
  workflow_dispatch:

env:
  BUILD_OUTPUT: 'build/Build/Products/Debug'
  MACOSX_DEPLOYMENT_TARGET: '26.0'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Manage Version
      run: |
        git fetch --tags --quiet
        GIT_SHA="$(git rev-parse --short HEAD)"
        eval $(grep -m 1 "MODULE_VERSION =" itlwm.xcodeproj/project.pbxproj | tr -d ';' | tr -d '\t' | tr -d " ")
        echo "SHORT_SHA=$GIT_SHA" >> $GITHUB_ENV
        echo "ITLWM_VER=$MODULE_VERSION" >> $GITHUB_ENV

    - name: Install MacKernelSDK
      run: |
        bash scripts/setup_mackernelsdk.sh

    - name: Build itlwm
      run: |
        xcodebuild -project itlwm.xcodeproj -scheme itlwm -configuration Debug -derivedDataPath build MACOSX_DEPLOYMENT_TARGET=26.0 GIT_COMMIT=_${SHORT_SHA}

    - name: Build AirportItlwm
      run: |
        xcodebuild -project itlwm.xcodeproj -scheme "AirportItlwm (all)" -configuration Debug -derivedDataPath build MACOSX_DEPLOYMENT_TARGET=26.0 GIT_COMMIT=_${SHORT_SHA}

    - name: Pack Artifacts
      run: |
        cd "$BUILD_OUTPUT"
        for tgt in *.kext; do
          zip -r "${tgt%.kext}-v${ITLWM_VER}-DEBUG-alpha-${SHORT_SHA}.zip" "$tgt"
        done
        cd -

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: itlwm-v${ITLWM_VER}-alpha-${SHORT_SHA}
        path: ${{ env.BUILD_OUTPUT }}/*.zip
