name: Build itlwm

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Xcode
        uses: apple-actions/setup-xcode@v2
      - name: Install dependencies
        run: |
          brew install cmake
          # Если есть зависимые библиотеки, установите их здесь
      - name: Build itlwm
        run: |
          xcodebuild -scheme AirportItlwm -configuration Debug -derivedDataPath build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: itlwm-build
          path: build
